apiVersion: apps/v1
kind: Deployment
metadata:
    name: sd-back
spec:
    replicas: 1
    selector:
        matchLabels:
            app: sd-back
    template:
        metadata:
            name: sd-back
            labels:
                app: sd-back
        spec:
            containers:
            - name: sd-back
              image: yourdockerhubid/service-discovery:latest
              imagePullPolicy: Always # to conserve on pulling can change to not allways pull
              env:
              - name: RETURN_VALUE
                value: "sd-back"
              ports:
              - name: http-port
                containerPort: 8080
              resources:
                  requests:
                      cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
    name: sd-back
spec:
    type: NodePort
    selector:
        app: sd-back
    ports:
    - port: 8080
      nodePort: 31003
