apiVersion: apps/v1
kind: Deployment
metadata:
    name: sd-front
spec:
    replicas: 1
    selector:
        matchLabels:
            app: sd-front
    template:
        metadata:
            name: sd-front
            labels:
                app: sd-front
        spec:
            containers:
            - name: sd-front
              image: yourdockerhubid/service-discovery:latest
              imagePullPolicy: Always # to conserve on pulling can change to not allways pull
              env:
              - name: RETURN_VALUE
                value: "sd-front"
              - name: DEPENDENCIES
                value: "sd-back.default.svc.cluster.local:8080"
              ports:
              - name: http-port
                containerPort: 8080
              resources:
                  requests:
                      cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
    name: sd-front
spec:
    type: NodePort
    selector:
        app: sd-front
    ports:
    - port: 8080
      nodePort: 31002